### ISSUE TITLE
Expected input shape error when using (B, W, C) convention

### ISSUE THREAD

**Issue by LukasMahieu** [jmschrei/tangermeme#19]
Hey Jacob,

We're running into an issue with the expected input shapes of our models.  
Since we follow tensorflow convention (for historical reasons) all our models have an expected input shape of (B, W, C). 
This is no problem for the package functionality that's not shape dependent (such as the predict function), however some other functions (such as deepLIFT) seem to expect the torch convention of (B, C, W).  
Is there an easy workaround here where we don't have to transpose all layers of our models? 

Thanks!

```python

import torch
from tangermeme.utils import random_one_hot
from tangermeme.predict import predict
from tangermeme.deep_lift_shap import deep_lift_shap

# Generate random sequence and reshape to (B, W, C)
X = random_one_hot((1, 4, 2114)).type(torch.float32).reshape(1, 2114, 4)

# predict: works
predict(keras_3_model, X)

# deepLIFT: won't work
X_attr = deep_lift_shap(keras_3_model, X, random_state=0)
X_attr
```

Results in:
**ValueError: X must be one-hot encoded and cannot have unknown characters.** (failed in dinucleotide shuffle() )

**Comment by jmschrei** [comment]
Oh, that's interesting. I would've thought that keras would handle changing the dimensions, or have some built-in utility for that, given that this is such a known issue.

I've found that the best way to get around these sorts of issues is to just create a wrapper. For example:

```python
class PermuteWrapper(torch.nn.Module):
    def __init__(self, model):
        self.model = model

    def forward(self, X):
        return self.model(X.permute(0, 2, 1))

model = PermuteWrapper(model)
```

**Comment by LukasMahieu** [comment]
Right, I guess it won't get much simpler than this. Been playing around a bit with tangermeme, seems very fast and works nicely with our models, thanks for the work!
