### ISSUE TITLE
Documentation on machine precision could use clarification

### ISSUE THREAD

**Issue by sandyfloren** [jmschrei/tangermeme#2]
Thanks for putting this together! The tutorials are very clear and easy to follow. 

I noticed that these two highlighted sentences in the DeepLIFT/SHAP tutorial contradict one another, since by "higher precision" one usually means "smaller numerical differences." If smaller convergence deltas should be expected on CPU, then maybe "GPU" and "CPU" should be swapped in the first sentence.

![image](https://github.com/jmschrei/tangermeme/assets/62759566/bae8643c-c3a9-42b5-a613-ab30a0405777)

**Comment by jmschrei** [comment]
Oops, good point. I need to swap GPU and CPU there.

**Comment by jmschrei** [comment]
This has been fixed internally and will appear on the documentation site soon.
