### ISSUE TITLE
Non ACGTN characters in FASTA cause error with `one_hot_encode` in `extract_matching_loci`

### ISSUE THREAD

**Issue by adamklie** [jmschrei/tangermeme#7]
Was creating some matched negatives with `match.extract_matching_loci` and discovered that my FASTA file contains many non-ACGTN IUPAC characters (e.g. 'B', 'K', etc). https://en.wikipedia.org/wiki/FASTA_format has their definitions. 

This causes tangermeme to raise an error with `one_hot_encode` anytime you don't have access to the `ignore` parameter. This was the fasta I was using: https://www.encodeproject.org/files/GRCh38_no_alt_analysis_set_GCA_000001405.15/@@download/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz

Not sure how you want to handle this. Might be specific to this FASTA and I don't know the total number of these characters that exist. Easiest would just to be to include all the IUPAC characters as the default. Could also be worth exposing those as parameters to relevant functions.

**Comment by jmschrei** [comment]
I think that I need to make the default in bpnet-lite to be to ignore all non-ACGT characters. I'll look into this soon.

**Comment by jmschrei** [comment]
This should be fixed in v0.2.3, which is now available on PyPI. Please let me know if there are still issues.
