### ISSUE TITLE
DeepSEA Beluga model in tutorial

### ISSUE THREAD

**Issue by maplecai** [jmschrei/tangermeme#8]
Thank you for this excellent package and tutorials! It helps me a lot.

In `tangermeme/docs/tutorials/Tutorial_A3_Deep_LIFT_SHAP.ipynb` 
```
import torch
from model import Beluga

model = Beluga()
model.load_state_dict(torch.load("deepsea.beluga.torch"))
```
The tutorial doesn't mention where model weights can be downloaded. I download DeepSEA Beluga model weights from <https://zenodo.org/records/3402406>. But my logo plot doesn't look right.
![1](https://github.com/jmschrei/tangermeme/assets/48918620/2d4271c8-a9df-4c3c-8238-3a2160249425)

I noticed in `tangermeme/docs/tutorials/model.py` that the alphabet order was changed manually. I think this might be some bug you found and fixed earlier.
```
    def forward(self, x):
        return self.model(x[:, [0, 2, 1, 3]].unsqueeze(2))
```
After I fixed this, my logo plot looks right.
```
    def forward(self, x):
        return self.model(x.unsqueeze(2))
```
![2](https://github.com/jmschrei/tangermeme/assets/48918620/11e21cc3-12f6-4507-880e-5ab880d64678)

Please check if this is due to our models weights being different or something else.
Thanks!

**Comment by jmschrei** [comment]
I downloaded the model weights from https://zenodo.org/record/3402406/files/deepsea.beluga.pth?download=1, where kipoi has them stored: https://github.com/kipoi/models/blob/master/DeepSEA/beluga/model.yaml

DeepSEA/Beluga's alphabet is AGCT, so you need to flip it to get everything working right.

**Comment by maplecai** [comment]
That's weird. I downloaded model weights from the link you provided. But my results are as I showed above. the DeepSEA Beluga model doesn't seem to need to flip the alphabet.

**Comment by jmschrei** [comment]
I think I forgot to re-run the tutorials after realizing the issue with the Beluga alphabet. I'll re-run them today and post fixed versions of the notebooks.

**Comment by maplecai** [comment]
Thanks! Looking forward to the new version!

**Comment by maplecai** [comment]
Hi, Jacob!

I think I identified the real issue. The Beluga model needs to flip G/C. The AP-1/JunD motif in the tutorial is incorrect. It should be GTGACTCATC {https://jaspar.elixir.no/matrix/MA0491.1}. This sequence matches the tutorial's sequence after flipping G/C.

**Comment by jmschrei** [comment]
This should be fixed in all the tutorials now. Please re-open if issues persist.
